### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by ghost** [EyeDaleHim/Platinum-Engine#1]
I look into things other people program for Friday Night Funkin', it's a long story. Basically, its partly the reason why I made my own engine, I was just not satisfied with using anyone else's projects at the time, and still am not. I'll spare you the details, as its best to just get to the point. 

![image](https://user-images.githubusercontent.com/37424048/126843760-d4ae8cbf-7dc4-4c46-bb31-83e925874204.png)

Please properly credit people in your projects, I'm not a fan of Kade at all whatsoever, in fact, I think his engine is hard to work with, but that doesn't matter because he still deserves credit given the fact you're using his code.

If you don't want to credit someone, don't use their code, it's kind of that simple. You can always reach out to other people, the FNF community has a lot of artists and programmers willing to collaborate who could help you make your own original engine.

Please properly credit people, and good luck with your future projects!

**Comment by EyeDaleHim** [comment]
There's a reason why it's open-source? Although you are in the world of Friday Night Funkin' we're allowed to do anything we want with it.

Although I will look (or think) about it.

**Comment by ghost** [comment]
Open Source means you can use the code, not steal it, you still have to credit the authors, just like how you wouldn't steal Friday Night Funkin' and claim its yours because its ninjamuffin's game.
